name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm  # 官方推荐的 pnpm 安装方式
        uses: pnpm/action-setup@v2
        with:
          version: 8  # 指定 pnpm 版本（可选）

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build