name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          # 强制设置 pnpm 的存储目录到项目内
          dest_dir: ./pnpm-store

      - name: Restore dependencies cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ./pnpm-store
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies (skip if cached)
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: |
          # 修复权限问题（避免使用 sudo）
          chmod -R 755 .
          pnpm install --frozen-lockfile --store-dir=./pnpm-store
        working-directory: ./

      - name: Build
        run: pnpm run build
        working-directory: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vitepress/dist