name: Deploy VitePress site to Pages

on:
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # 缓存 VitePress 构建产物
      - name: Cache VitePress
        uses: actions/cache@v3
        with:
          path: |
            .vitepress/cache
            .vitepress/.temp
          key: vitepress-cache-${{ hashFiles('/**/*.md') }}-${{ hashFiles('/.vitepress/config.ts') }}
          restore-keys: |
            vitepress-cache-

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: |
          pnpm run build
          touch .vitepress/dist/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .vitepress/dist
          branch: gh-pages
          clean: true