name: Deploy

on:
    push:
        branches:
            - fake

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   uses: oven-sh/setup-bun@v2
            -   run: bun install

            -   name: Build
                run: bun run build

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: .vitepress/dist
